### ISSUE TITLE
My issue is Confusion

### ISSUE THREAD

**Issue by apatton724** [rboddy/1HoC#1]
- Where has Ryan been?
- What is he working on?
- What should we expect from him in the next 1-3 years?
- How's marriage?

I can go on forever. I know where ever he is, he's being productive!

**Comment by rboddy** [comment]
Hey man! I will shoot you a text! I chuckled when I saw an open issue. Great to hear from you!

**Comment by apatton724** [comment]
Thanks for clearing up my confusion!
